export const DOMAIN_DATA= [
    {
      id:0,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:1,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:2,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:3,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:4,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:5,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:6,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:7,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:8,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:9,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:10,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:11,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:12,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:13,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:14,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:15,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
        {
      id:16,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:17,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:18,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:19,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:20,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:21,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:22,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:23,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:24,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:25,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:26,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:27,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:28,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:29,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
    {
      id:30,
      tld: 'com', available:'true', isPremium:'false',
      Price:'5.00$',
      RenewalPrice:'10.00$',
    },
]